### ISSUE TITLE
Ongoing Refactoring

### ISSUE THREAD

**Issue by typhonrt** [typhonjs-node-esdoc/esdoc#1]
Please see info about a new [permanent fork of ESDoc](https://github.com/typhonjs-node-esdoc/esdoc/issues/6) in the works for Q1 2017.

Please stay tuned to this issue for ongoing refactoring details:
## (2016-07-24)
- An experimental branch supporting multiple source paths via file globs is available for review. Please review https://github.com/esdoc/esdoc/issues/310  for details.
## (2016-06-06)
- Support for Babylon is now integrated w/ all plugins supporting all edge / ES7 code. 
## (2016-06-04)
- Removed unnecessary dependencies (core-js, etc.)
- Fully integrated `typhonjs-npm-build-test` and removed local scripts.
- Swapped out `estraverse` for `typhonjs-ast-walker`
## (2016-06-02)
- Updated all dependencies
- Fixed issue with espree to support [trailingComments](https://github.com/typhonjs-node-esdoc/esdoc/blob/master/src/Factory/DocFactory.js#L51-L54)
- Added coverage for ES6 tests
- Removed unnecessary code (web site)
- Had to check in transpiled code to link ESDoc from Github
- To include in your project add to package.json: `"esdoc": "git+https://git@github.com/typhonjs-node-esdoc/esdoc.git"`
- added additional data to existing callbacks [(commit)](https://github.com/typhonjs-node-esdoc/esdoc/commit/52b9e14149ebf4b7fb990aed7ec90590b0c0a0ad)

**Comment by hmil** [comment]
Hi,

Glad to see you've put some effort into giving esdoc some fresh air :+1: 

My two cents on the ongoing refactoring:
- Could you explain what typhonjs-npm-build-test brings to the project ?
- v4 is the current lts and [is scheduled to live until 2018](https://github.com/nodejs/LTS#lts_schedule). I know for a fact that many still use v4 and I think it is well worth the effort supporting v4 as long as it is on the schedule.

**Comment by typhonrt** [comment]
Hi @hmil, first it should really be pointed out that Node v5+ / NPM 3+ is only necessary if one is working on development of ESDoc (or any repo adopting the TyphonJS NPM build tooling). The crux of Node 5+ / NPM 3+ adoption that is being capitalized on is the [flat packages](https://docs.npmjs.com/how-npm-works/npm3) nature of this release and forward. A single developer dependency on [typhonjs-npm-build-test](https://www.npmjs.com/package/typhonjs-npm-build-test) is able to pull in a comprehensive build / test / documentation / publish tool chain instead of individually referencing all the dependencies encompassed in every repo that may adopt this pattern. I guess you can consider it like free peer dependencies. 

I do all development on an OSX laptop w/ WebStorm and it's super easy to upgrade to Node 5+. If you are a developer upgrading should not be a concern. Any downstream user of ESDoc isn't affected as this is only a development concern and the benefit of pulling in a complete tool chain with a single developer dependency IMHO at least is compelling.

**Comment by typhonrt** [comment]
Please see #6 regarding a new permanent fork of ESDoc that will be released shortly with a significantly enhanced architecture with a goal of supporting Flow in addition to Typescript along with ES6+ support.
