### ISSUE TITLE
Support for inline functions

### ISSUE THREAD

**Issue by raveclassic** [typhonjs-node-esdoc/esdoc#3]
Hi! 

Firstly, thanks for the fork and the effort for bringing esdoc back to live!

I'm trying to inline type for callback but with no luck:

``` javascript
/**
 * @param {function(number):string} cb
 */
function foo(cb) {
    /**
     * @type {string} - inferred and autogenerated by WebStorm on '/**+enter'
     */
    const result = cb(''); //warning about passing string instead of number
}
```

Are you going to support such notation as a maintainer of this fork? This would realy help because currenly I need to define dedicated typedef/callback type for this function.

To be honest I don't see such notation in jsdoc spec but WebStorm supports it.
Thanks!

UPDATE:
This ends up with error at `esdoc\out\src\Publisher\Builder\DocBuilder.js:924:34`:
`TypeError: Cannot read property 'replace' of undefined`

**Comment by typhonrt** [comment]
It looks like you're trying to use closure compiler syntax for the `@param`. 

This should work: 

```
/**
 * @param {function(param: number): string} cb - A callback
 */
function foo(cb) {
    // You can't use `@type` here as it is only picked up for member variables and get / set methods.
    const result = cb(''); //warning about passing string instead of number
}
```

Also consider adding `"unexportIdentifier": true` to your ESDoc config file if the function isn't exported.

`@param {function(param: number): string} cb` gets picked up fine by WebStorm and delivers the same warning as the closure compiler syntax and generates ESDoc output for it.

---

As far as moving this fork further I really really really want to try and upstream it. The v1.0 post the esdoc maintainer left about a month ago I could complete in ~1 day as this fork already has done the hard parts listed such as switching to babylon.

If there is no progress in main esdoc repo in the next month I'll make one more plea to the maintainer before really splitting off with this fork which will make it incompatible soon after. 

---

If it comes to making a permanent fork I plan to try and expose all of the internal hard coded paths currently in ESDoc with a bunch of plugin hooks to implement the default setup as a bunch of internal plugins which could then be overridden or added to if folks want to create plugins to support closure compiler syntax or flow typing support for instance.

**Comment by raveclassic** [comment]
Yes, explicit arg names helped, thanks!

One more thing: your fork does not launch without manually installing `babel-polyfill` - why do you need it?

**Comment by typhonrt** [comment]
huh.. oh... good catch, I added it to `dependencies` of my ESDoc fork. I happen to always install [typhonjs-npm-build-test](https://www.npmjs.com/package/typhonjs-npm-build-test) as a dev dependency in my repos which will pull in all of Babel 6 and my fork of ESDoc. `babel-polyfill` is a more complete polyfill which includes `core-js`. You can see in the main ESDoc repo which is older / before Babel 6 support that it [depends on core-js](https://github.com/esdoc/esdoc/blob/master/package.json#L23).

It basically allows a full ES6 + some future features of ES7 [to be used](https://babeljs.io/docs/usage/polyfill/).
